### ISSUE TITLE
Suggestion for chrono::duration in Console

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#10]
It seems that the following (along the lines of http://en.cppreference.com/w/cpp/chrono/duration/duration_cast) would work better for displaying time differences:

```
 std::chrono::duration<double, std::milli> doubleMs = now - (*found).second;
write(INFO,"Console::timeEnd('{}'): {}", label, doubleMs.count());
```

Same proposal stands for the second place where `chrono::duration_cast<>` is used.

**Comment by dl-dl** [comment]
Done.
