### ISSUE TITLE
Support for chained Future::then()?

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#19]
For reference: equivalent blocking code would look as follows:

```
    void run() override {
        std::string fname( "path1" );
        Buffer data = FS::readFile( this, fname.c_str() );
        infraConsole.log( "READ1: file {}---{}", fname.c_str(), data.value().toString() );
        Buffer data2 = FS::readFile( this, "path2" );
        infraConsole.log( "READ2: {} : {}", data.value().toString(), data2.value().toString() );
        Buffer data3 = FS::readFile( this, "path3" );
        infraConsole.log( "READ3: {} : {}", data.value().toString(), data3.value().toString() );
        }
```

Currently the sample code (equivalent to blocking one above) goes as follows:

```
    void run() override {
        std::string fname( "path1" );
        Future< Buffer > data = FS::readFile( this, fname.c_str() );
        data.then( [ = ]() {
            infraConsole.log( "READ1: file {}---{}", fname.c_str(), data.value().toString() );
            Future< Buffer > data2 = FS::readFile( this, "path2" );
            data2.then( [ = ]() {
                infraConsole.log( "READ2: {} : {}", data.value().toString(), data2.value().toString() );
                Future< Buffer > data3 = FS::readFile( this, "path3" );
                data3.then( [ = ]() {
                    infraConsole.log( "READ3: {} : {}", data.value().toString(), data3.value().toString() );
                } );
            } );
        } );
    }
```

This is ok (well, better than "callback hell"), but is too reminiscent of "lambda pyramid" (and the main problem is that the code is not exactly linear). Guys here: https://code.facebook.com/posts/1661982097368498/futures-for-c-11-at-facebook/ describe an alternative way of doing the same thing with futures. For our case, it would look as follows:

```
    void run() override {
        std::string fname( "path1" );
        Future< Buffer > data = FS::readFile( this, fname.c_str() );
        Future<Buffer> data2(this);//not completely initialised (yet); DOES have a corresponding InfraFuture, but does NOT wait for anything
        Future<Buffer> data3(this);//see comment above
        data.then( [ = ]() {
            infraConsole.log( "READ1: file {}---{}", fname.c_str(), data.value().toString() );
            data2 = FS::readFile( this, "path2" );
            })
         .then(data2, [=](){
            infraConsole.log( "READ2: {} : {}", data.value().toString(), data2.value().toString() );
            data3 = FS::readFile( this, "path3" );
         })
         .then(data3, [=](){
            infraConsole.log( "READ3: {} : {}", data.value().toString(), data3.value().toString() );
         });
    }
```

Question 1: do we want to support it (IN ADDITION to existing "ladder" style)? (IMHO yes: the code does IMHO read better - it is just more linear this way)
Question 2: can we support it? IMHO yes. Our concept of Futures doesn't change, and we DO know what we're waiting for at the each of then() points. Also I do NOT see a need to use something like `list<FutureFunction>` in InfraFutureBase: instead, we can add InfraFutureBase\* InfraFutureBase::chainedFuture, and to start waiting for an event for chainedFuture after our current Future has finished processing; at this point we MUST check that chainedFuture already has something-to-wait-for (otherwise it is malformed program).

@marcosbracco and @divanchykhin, PLEASE COMMENT ON QUESTION 1!

**Comment by divanchykhin** [comment]
Yes, in general, we do with a reason of readability (as a self-check: just try to add one more item in each of them; imho, in the last sample it's easier to figure out what to do).

**Comment by dl-dl** [comment]
Readability of conditional calls should be considered as well.

**Comment by nobugs-hare** [comment]
@dl-dl : you're right; see new proposal for CCode in issue #20.
