### ISSUE TITLE
Style / naming to make Autom consistent with NJS - round 1

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#21]
- autom::FS::createServer() should become autom::net::createServer() (probably with autom::net being a namespace)
- autom::net::createServer() should return some (TcpServer?) object, which would then have a listen() method (and it is listen() method which will return `MultiFuture<TcpConnection>`)
- `Future<>.getId()` should be either removed, or renamed into `Future<>.infraGetId()`
- TcpServerConn::read() probably should return MultiFuture, right?
- to be consistent with Node.js, we'd need to rename TcpServerConn::read() into TcpServerConn::data() - not that I really like it, but let's try
- autom::FS::startTimer() should be renamed into autom::setTimeout() (returning Future) and autom::setInterval() (returning MultiFuture) with parameters along the lines of these functions as described here: https://nodejs.org/api/timers.html
- let's rename class FS into class InfraNodeContainer

File-wise:
- let's move all the autom::net stuff (which will appear after we rename things according to the above) into a separate net.h/net.cpp 
- let's move all the autom::InfraNodeContainer (former class FS) to separate files (with header being in libsrc/infra/nodecontainer.h or something along the same lines).

**Comment by dl-dl** [comment]
Implemented.
