### ISSUE TITLE
Mismatching '{' in CCODE syntax

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#23]
Currently, it seems that the minimal CCODE will look as follows:

CCODE {
ENDCCODE

which indicates a mismatch in '{' / '}'. To deal with it, I suggest to remove opening '}' from definition of ENDCCODE, then the code above will look as

CCODE {
}
ENDCCODE

which is IMO more natural.

**Comment by dl-dl** [comment]
Fixed.
