### ISSUE TITLE
Run astyle on existing sources

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#7]
Currently formatting is a mess (due to different editors etc.). Let's try to run the latest greatest astyle over the source (with no command-line parameters). If it won't look good - let's experiment with parameters.

As soon as parameters are found - let's run it every time before committing to develop branch.

**Comment by dl-dl** [comment]
> Run astyle without parameters
> Done. Please review.  In my opinion it's not satisfactory.

**Comment by nobugs-hare** [comment]
IMHO: 
1. it is MUCH better than before (which was a complete mess).
2. I can live with this one.

Therefore: 
1. Let's use astyle from now on (as even this is MUCH better than mess before)
2. If you find a better combination of astyle flags (or even a new tool) - feel free to try.

Ok?

**Comment by dl-dl** [comment]
OK.
