### ISSUE TITLE
On make_pair vs value_type when inserting into map<>

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Autom.cpp#9]
I tend to prefer `value_pair<>`, and it is also supported in the community (as more strict and marginally faster in some cases as a result): see, for example, here: http://stackoverflow.com/questions/17172080/insert-vs-emplace-vs-operator-in-c-map

PLEASE COMMENT, and if you agree with the logic - please change it to `value_pair<>` where applicable (and I will add it to STYLE-GUIDE too).

**Comment by dl-dl** [comment]
Agree. Done.

**Comment by nobugs-hare** [comment]
Added to STYLE-GUIDE, closing the issue
